<?xml version="1.0"?>
<!DOCTYPE document[
<!ELEMENT document (customer)*>
<!ELEMENT customer (name,date,orders)>
<!ELEMENT name (lastname,firstname)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT orders (item)*>
<!ELEMENT item (product, number, price)>
<!ELEMENT product (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT price (#PCDATA)>
]>
<document>
   <customer>
        <name>  
           <lastname>aaa</lastname>
           <firstname>bbb</firstname>
        </name>
        <date>3 jan 2023</date>
        <orders>
           <item>
              <product>fruits</product>
              <number>120</number>
              <price>250</price>
           </item>
        </orders>
    </customer>
</document>
             
    

